# Generated by Django 6.0 on 2025-12-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='annee',
            fields=[
                ('NUM_ANNEE', models.IntegerField(db_column='NUM_ANNEE', primary_key=True, serialize=False)),
                ('DESIGNATION_ANNEE', models.CharField(db_column='DESIGNATION_ANNEE', max_length=100)),
                ('NATURE_ANNEE', models.CharField(db_column='NATURE_ANNEE', max_length=10)),
            ],
            options={
                'db_table': 'ANNEE',
                'managed': False,
            },
        ),
    ]
